name: Daily GitHub Activity Email Report

on:
  schedule:
    # Runs at 9:00 AM Nepal time (3:15 AM UTC)
    - cron: "15 3 * * *"
  workflow_dispatch:
    inputs:
      force_send:
        description: 'Send email even on weekends/holidays'
        required: false
        default: 'false'
        type: boolean

jobs:
  send-daily-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install PyGithub pytz

      - name: Send Daily Activity Email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          FORCE_SEND: ${{ github.event.inputs.force_send }}
        run: |
          python scripts/github_activity_emailer.py